#To Print a Address Scan model in Python#
Name=input("Enter the Name")
Sonof=input("Enter the Sonos")
Doorno=input("Enter the Door no")
Street=input("Enter the Street")
Town=input("Enter the Town")
pincode=input("Enter the Pincode")
State=input("Enter the State")
print("Name is   :",Name)
print("Sonof is  :",Sonof)
print("Doorno is :",Doorno)
print("Street is :",Street)
print("Town is   :",Town)
print("Pincode is:",pincode)
print("State is  :",State)
